// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtwbukbawerheuknftwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0d2J1a2Jhd2VyaGV1a25mdHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjYyMDQsImV4cCI6MjA2NTg0MjIwNH0.PC9ejoDafvEDKuzpM3EnIQoQpxdFUqA5ERb97qlYKbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);